# Generated by Django 5.0.6 on 2024-11-13 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nro_departamento', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('año', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.BooleanField(default=False)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.residente')),
            ],
        ),
    ]
